server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://banco:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

services.estudante.url=${SERVICES_ESTUDANTE_URL:http://estudante-service:8080}
services.disciplina.url=${SERVICES_DISCIPLINA_URL:http://disciplina-service:8080}
